### ISSUE TITLE
Wineasio in manjaro problem

### ISSUE THREAD

**Issue by dimonleonov** [wineasio/wineasio#27]
Hello. There is a problem with wineasio working in manjaro. I am using manjaro with kernel 5.13.1, wine-6.12 (Staging).
I installed wineasio from the AUR because I could not build it from source (`make 32` / `make 64` output is "_There is no rule for building the rtaudio / include / asio.h target required for build. Stop._")

It was possible to install with AUR, however, unfortunately, even after regsvr32 wine still refuses to see the wineasio driver (in winecfg, in the sound tab I see only good old pulseaudio). The DAW also, logically, does not see wineasio.
![image](https://user-images.githubusercontent.com/10165708/126534666-6739bc68-51a4-46ee-ad4c-13156df7045c.png)
P.s. `regsvr32` says about success installed DLLs.

What am I doing wrong? :)

AUR: https://aur.archlinux.org/packages/wineasio/

**Comment by mickski56** [comment]
I think your build problem is because you did a git clone without git submodule init, git submodule update afterwards.

wineasio does not appear in winecfg this is normal. You select it from your asio compatible sound application. Though you may need to follow the discussion in https://github.com/wineasio/wineasio/issues/24 for recent versions of wine, which yours is.

**Comment by falkTX** [comment]
That is correct, the git repo has submodules which need to be there in order to build.
I added a comment in AUR to explain the new steps needed to register wineasio
